### PR TITLE
[NodeValue] Provide methods to access the users of a NodeValue

### LINKED ISSUE #1346: Our def-use chains are counter intuitive (and error-prone IMHO)
When we have nodes with several outputs (like TopK or MeanVarNormalization), we don't track the def-use chain per output but instead we do it per node.

In effect, imagine we have something like:
auto *topK = createTopK
auto *values = topK.getValues();
auto *indices = topK.getIndices();

Walking the users for all three variables will give us the exact same def-use chain.

So for instance, walking through the users of indices and doing some changes without checking that the use is of the right NodeValue (i.e., checking that the ResNos are the same) will produce incorrect code.

Another instance is checking hasOneUse for values could be false because indices could also be used.

replaceAllUsesOfWith does the right thing, but one would expect that the number of updates that function does is equal to the number of users the related value has. Right now, it is not the case.

This bit me when I was writing some asserts where I thought the NodeValue would have one use.

I'll write a test case to show the issue.

### PR DESCRIPTION
**Pull request by qcolombet**
Prior to this patch the only way to get to the users of a node value
was to get through the users of the related node and filtered out
the uses of that did not match the result number.

This feature is now directly accessible through the NodeValueIterator
class and exposed via the new methods NodeValue::getUsers,
NodeValue::getNumUsers, and NodeValue::hasOneUse.

This fixes #1346.

### CODE REVIEW

File: tests/unittests/graphTest.cpp [hunk 1]
```diff
@@ -641,6 +643,19 @@ TEST(Graph, cmpOutputTypes) {
...
 }
 
+/// Check that the users of value are equal to expectedUsers.
+static bool
+hasAllTheseUses(const llvm::SmallPtrSetImpl<const Node *> &expectedUsers,
+                const NodeValue &value) {
+  llvm::SmallPtrSet<const Node *, 4> uses;
+  for (const NodeUse &users : value.getUsers()) {
+    const Node *user = users.getUser();
+    EXPECT_TRUE(expectedUsers.count(user));
```
Comment (jfix71) [inline tests/unittests/graphTest.cpp]: It's a little funny that this function could still return true even if there's a failure here. Maybe you want to just return false here instead of `EXPECT_TRUE()`? Or you could turn this into a `void` function and `EXPECT_TRUE()` on the size comparison at the bottom here.

File: include/glow/Graph/Node.h [hunk 2]
```diff
@@ -352,6 +365,84 @@ class NodeWalker {
...
+  NodeValueIteratorImpl(NodeValueTy &parent, iterator it)
+      : parent_(parent), it_(it) {
+    if (it_ != getEnd() && !hasSameParent()) {
+      ++(*this);
+    }
+    assert((it_ == getEnd() || hasSameParent()) &&
+           "operator++ should return the next valid iterator");
+  }
+
+  const NodeValueTy &getParent() const { return parent_; }
```
Comment (jfix71) [inline include/glow/Graph/Node.h]: This doesn't seem to be used -- should it be removed, or be made private? Otherwise I think it should be included in the unit test.

Comment (qcolombet) [reply include/glow/Graph/Node.h]: Good catch, I meant to test it :)

File: tests/unittests/graphTest.cpp (hunk 1 above)
Comment (qcolombet) [reply tests/unittests/graphTest.cpp]: Returning false would be the right thing to do.
I don't know what I was thinking.

**Comment by qcolombet** [comment]
Thanks @jfix71 for the review! I'll add a test case for node with only one result.

File: include/glow/Graph/Node.h (hunk 2 above)
Comment (qcolombet) [reply include/glow/Graph/Node.h]: Finally I decided to drop it. I meant to add some asserts in the test, but I actually already did the checks I wanted within the class (::hasSameParent).

File: tests/unittests/graphTest.cpp (hunk 1 above)
Comment (qcolombet) [reply tests/unittests/graphTest.cpp]: Done.

**Comment by qcolombet** [comment]
Test added for single result nodes.

**Comment by nadavrot** [comment]
Nice!
