### PR TITLE
Resize output of FC with dims > 2

### LINKED ISSUE #2522: Need to output correct shape for C2 FC op
Today, if the input X or W for FC op has dim higher than 2, they will be flattened into 2D along `axis` or `axis_w`:
https://github.com/pytorch/glow/blob/143f862e7c5bd19b050c5865f3b465c7e5986185/lib/Importer/Caffe2ModelLoader.cpp#L569

And output will be 2D. This creates semantic difference between Glow and C2 ops, because c2's output shape will have the same dim size as input. The consequence is that if we have ` FC -> Transpose` sequence, with FC having 4D input and Transpose having 4D perms arguement, you will meet with a segfault, as Transpose is trying to access 4D dim of the input. 

The solution should be adding a `Reshape` node after FullyConnect layer when importing C2 FC op and when its input is more than 2D. The spec of the Reshape can be computed using:
https://github.com/pytorch/pytorch/blob/c10662962c5ea7da9762be65eacafee376d9c13c/caffe2/operators/fc_inference.cc#L4-L33

### PR DESCRIPTION
**Pull request by jackm321**
*Description*:
We need to match the behavior of Caffe2. When number of input dimensions to FC is greater than 2, Glow flattens down to 2 dimensions using axis but does not reshape the output back to original dimensions before the axis.

*Testing*:
Create a new C2 Graph and test that the output shape is the expected shape.

*Documentation*:
Fixes #2522

### CODE REVIEW

File: lib/Importer/Caffe2ModelLoader.cpp [hunk 1]
```diff
@@ -624,6 +628,18 @@ llvm::Error Caffe2ModelLoader::loadOperator(const caffe2::OperatorDef &op) {
       node = G_.createFullyConnected(opName, in, W, B);
     }
 
+    // If number of original input dims is greater then expand the output dims
+    // back with the same axis.
+    if (originalInputDims.size() > 2) {
```
Comment (yinghai) [inline lib/Importer/Caffe2ModelLoader.cpp]: You should check the whether the number of elements is the same?

File: tests/unittests/Caffe2ImporterTest.cpp [hunk 2]
```diff
@@ -798,79 +769,81 @@ TEST(caffe2, FCTransposed) {
...
-    for (size_t i = 0; i < expectedValues.size(); ++i) {
-      EXPECT_FLOAT_EQ(expectedValues.at(i), elements.raw(i))
-          << "Where i = " << i;
-    }
-  }
-
-  // We don't actually check that the output is correct, because this is
-  // already covered in the Operator.FCWithFlatten/* tests.
-}
+// TEST(caffe2, FCTransposedWithFlatten) {
```
Comment (hyuen) [inline tests/unittests/Caffe2ImporterTest.cpp]: uncomment this?

File: lib/Importer/Caffe2ModelLoader.cpp (hunk 1 above)
Comment (jackm321) [reply lib/Importer/Caffe2ModelLoader.cpp]: If everything is correct it will be but this check is also done by createReshape

File: tests/unittests/Caffe2ImporterTest.cpp (hunk 2 above)
Comment (jackm321) [reply tests/unittests/Caffe2ImporterTest.cpp]: I need to rewrite this test, it's wrong now

File: lib/Importer/Caffe2ModelLoader.cpp (hunk 1 above)
Comment (yinghai) [reply lib/Importer/Caffe2ModelLoader.cpp]: And you get a coredump? We want to avoid coredump.

**Comment by jackm321** [comment]
Still WIP, just putting this up now to unblock @yinghai, I still need to update tests and update the C++ api `Function::createFullyConnected(...)` to also do the right thing as well.

File: lib/Importer/Caffe2ModelLoader.cpp [hunk 3]
```diff
@@ -580,10 +584,10 @@ llvm::Error Caffe2ModelLoader::loadOperator(const caffe2::OperatorDef &op) {
     }
 
     // Caffe2 stores the transposed W matrix. In here we first coerce W to a 2D
-    // matrix size if necessay and then transpose it back.
+    // matrix size if necessary and then transpose it back.
     Tensor tmp;
+    auto wDims = flattenCdr(w->dims(), axis_w);
```
Comment (rdzhabarov) [inline lib/Importer/Caffe2ModelLoader.cpp]: qq: why do we flatten no matter what (check `w->dims().size() > 2` seems reasonable).

Comment (jackm321) [reply lib/Importer/Caffe2ModelLoader.cpp]: This doesn't flatten, it just finds the dims if we do flatten. I put this here so that it's accessible below.

File: lib/Importer/Caffe2ModelLoader.cpp (hunk 1 above)
Comment (jackm321) [reply lib/Importer/Caffe2ModelLoader.cpp]: Yeah right now we do but I have been pushing for putting all those check in to llvm::Errors as well so they will return back to c2. But sure for now I can add an additional check here

Comment (yinghai) [reply lib/Importer/Caffe2ModelLoader.cpp]: Is this condition correct? I think it should be conditioned on axis?

Comment (jackm321) [reply lib/Importer/Caffe2ModelLoader.cpp]: Do you have an example where this would not work?

File: lib/Importer/Caffe2ModelLoader.cpp [hunk 4]
```diff
@@ -624,6 +628,31 @@ llvm::Error Caffe2ModelLoader::loadOperator(const caffe2::OperatorDef &op) {
...
     }
 
+    // If number of original input dims is greater than 2, expand the output
+    // dims back with the same axis.
+    if (originalInputDims.size() > 2) {
+
+      llvm::SmallVector<size_t, max_tensor_dimensions> reshapeDims;
+      size_t totalReshapeSize = 1;
+      for (size_t i = 0; i < axis; ++i) {
+        auto d = originalInputDims[i];
```
Comment (rdzhabarov) [inline lib/Importer/Caffe2ModelLoader.cpp]: can you use concrete type here, it's not clear why there is static_cast below.

File: lib/Importer/Caffe2ModelLoader.cpp [hunk 5]
```diff
@@ -560,12 +560,16 @@ llvm::Error Caffe2ModelLoader::loadOperator(const caffe2::OperatorDef &op) {
     NodeValue in;
     ASSIGN_VALUE_OR_RETURN_ERR(in,
                                getNodeValueOrCreateConstantByName(op.input(0)));
-    if (in.getType()->dims().size() > 2) {
-      size_t axis = 1;
-      if (dict.count("axis")) {
-        ASSIGN_VALUE_OR_RETURN_ERR(axis, loadInt(dict["axis"]));
-      }
 
+    auto originalInputDims = in.getType()->dims();
```
Comment (rdzhabarov) [inline lib/Importer/Caffe2ModelLoader.cpp]: Can you document the expected behavior when flattening happens and how the resulted shape after FC should look like.

File: lib/Importer/Caffe2ModelLoader.cpp (hunk 1 above)
Comment (yinghai) [reply lib/Importer/Caffe2ModelLoader.cpp]: It will work in terms of correctness but we don't necessarily need to add Reshape whenever input dim is greater than 2, right?

Comment (jackm321) [reply lib/Importer/Caffe2ModelLoader.cpp]: We can do `axis != 1` and this should cover any case where output of conv should not be 2 dims right?

File: tests/models/caffe2Models/fc_4d_predict_net.pbtxt [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+op {
+  input: "inputs"
+  input: "weights"
+  input: "bias"
+  output: "fc_result"
+  name: ""
+  type: "FC"
+  arg {
+    name: "axis"
+    i: 3
```
Comment (yinghai) [inline tests/models/caffe2Models/fc_4d_predict_net.pbtxt]: We can have a case with `axis=1` for contrast.
