### PR TITLE
[Partitioner] If a proper partition is not found, return an error.

### LINKED ISSUE #2661: Unhelpful error message: "Provisioner found more logical devices than physical devices."
I think what this is trying to say is that I don't have enough memory to run my network?  Or I've configured my device manager with some incorrect amount of memory?  It's hard to know what to do with this string because "logical devices" isn't a terribly intuitive concept.

### PR DESCRIPTION
**Pull request by beicy**
*Description*:
If the number of devices is fewer than the number of partitions, we used to let Provisioner to report this error. Now we move the error detection into Partitioner.  If a proper partition can't be found, an error is reported.

Testing*:
Added unittest.

*Documentation*:
[Optional Fixes #2661 ]

Please see a detailed explanation of how to fill out the fields in the relevant sections in PULL_REQUEST.md.

### CODE REVIEW

File: lib/Partitioner/Partitioner.cpp [hunk 1]
```diff
@@ -546,7 +546,7 @@ void Partitioner::doPartitioning(Function *F, NodeToFunctionMap &mapping) {
   }
 }
 
-DAGListTy &Partitioner::Partition() {
+llvm::Error Partitioner::Partition() {
```
Comment (opti-mix) [inline lib/Partitioner/Partitioner.cpp]: Do we usually use `llvm::Error` or `llvm::Expected` in such cases, where a function is supposed to return a value?

Comment (beicy) [reply lib/Partitioner/Partitioner.cpp]: We use llmv::Error. If there is no error, the function will return `llvm::Error::success();`

File: include/glow/Partitioner/Partitioner.h [hunk 2]
```diff
@@ -157,7 +158,9 @@ class Partitioner {
   Partitioner(Module *parent, const std::vector<DeviceInfo> &devices);
 
   /// Decompose each function in a module and return a list of DAGNodes.
```
Comment (gcatron) [inline include/glow/Partitioner/Partitioner.h]: Probably should update the comment since this no longer returns the list of DAGNodes.

File: include/glow/Partitioner/Partitioner.h [hunk 3]
```diff
@@ -157,7 +158,9 @@ class Partitioner {
...
-  DAGListTy &Partition();
+  llvm::Error Partition();
+
+  DAGListTy &getPartitionResult() { return partitions_; }
```
Comment (gcatron) [inline include/glow/Partitioner/Partitioner.h]: Need a comment for getPartitionResult.
