### PR TITLE
[ModelZoo] Add RCNN ILSVC13 ONNX model

### LINKED ISSUE #2505: [ModelZoo] support R-CNN ILSVRC13 model
Add support for the R-CNN ILSVRC13 image detection model in glow (https://github.com/onnx/models/tree/master/bvlc_reference_rcnn_ilsvrc13) and verify via a runnable example we can include in the ModelZoo regression test.

We've had reports running this model that the outputs are not sensible (negative probabilities) so may indicate a bug.

This issue blocks #2500.

### PR DESCRIPTION
**Pull request by enferex**
*Description*:
This image classification model currently works with glow.  The
probabilities match those reported by Caffe2 model of this RCNN.  The
labels reported match the following list:  See Table 8
of https://arxiv.org/pdf/1311.2524.pdf

*Testing*:
`ninja all && ./tests/images/run.sh`
or
`bin/image-classifier tests/images/imagenet/cat_285.png -model bvlc_reference_rcnn_ilsvrc13/model.onnx -model-input-name data_0 -image-mode 0to255`

The result should identify that image as "Label-K1: 58"

Fixes #2505

### CODE REVIEW

File: tests/images/run.sh [hunk 1]
```diff
@@ -151,6 +152,15 @@ for png_filename in tests/images/EmotionSampleImages/*.png; do
   i=$(($i + 1))
 done
 
+# R-CNN ILSVRC13 ONNX Model: See Table 8 of https://arxiv.org/pdf/1311.2524.pdf
+# for the classication labels, they differ from thoes defined by imagenet.
```
Comment (jfix71) [inline tests/images/run.sh]: typo: "thoes"

**Comment by enferex** [comment]
> Awesome, LGTM, just one typo

Oh man! That's embarrassing.  Actually two typos, "classication" is another word my fingers made up.

**Comment by nadavrot** [comment]
@enferex Congrats on landing your first commits to the project. Thank you.
