### PR TITLE
[test] Legalize a name when the placeholer is updated by name.

### LINKED ISSUE #2565: Placeholder unique name
For each Placeholder, Glow will register a unique name for it. However, it may cause the function `updateInputPlaceholdersByName` failed. 
E.g. In Resnet50, the input is `gpu_0/data_0`, but it will be changed into `gpu_0_data_0`. When we want to use the following code to fit the input,  we will get an error "There is no tensor registered with name". 
```
 Caffe2ModelLoader caffe2LD(NetDescFilename, NetWeightFilename, {"gpu_0/data_0"}, 
                                                      {&data.getType()}, *F);
...
 updateInputPlaceholdersByName(bindings, &mod, {"gpu_0/data_0"}, {&data});
```
It looks to me that `updateInputPlaceholdersByName` is used in Glow's unittests only.  But I think it is better to do the same conversion.

### PR DESCRIPTION
**Pull request by beicy**
*Description*:
Since one placeholder's name will be legalized before registration, when we update one placeholder by name, the name should be processed in the same way. Otherwise, finding the placeholder may be failed.

*Testing*:
unittest.

*Documentation*:
[Optional Fixes #2565]

Please see a detailed explanation of how to fill out the fields in the relevant sections in PULL_REQUEST.md.

### CODE REVIEW

File: lib/ExecutionEngine/ExecutionEngine.cpp [hunk 1]
```diff
@@ -103,7 +103,13 @@ void glow::updateInputPlaceholdersByName(PlaceholderBindings &bindings,
          "The number of inputs does not match the number of Placeholders");
 
   for (int i = 0, e = ph.size(); i < e; i++) {
-    Placeholder *p = mod->getPlaceholderByName(ph[i]);
+    // Legalize the name.
+    std::string legalName;
```
Comment (rdzhabarov) [inline lib/ExecutionEngine/ExecutionEngine.cpp]: there are several places we do name legalization (see Graph.cpp), I'd suggest to place this in a Support lib and reuse in all those places.

File: include/glow/Support/Support.h [hunk 2]
```diff
@@ -111,6 +111,9 @@ void report(const char *msg);
 inline void report(const std::string &str) { report(str.c_str()); }
 inline void report(llvm::StringRef str) { report(str.data()); }
 
+/// Legalize \p name used in Module.
```
Comment (rdzhabarov) [inline include/glow/Support/Support.h]: could you add quick info here about what `legalize` would mean in this context.

File: lib/Support/Support.cpp [hunk 3]
```diff
@@ -99,4 +99,22 @@ const std::string strFormat(const char *format, ...) {
   va_end(vaArgs);
   return std::string(str.data(), len);
 }
+
+std::string legalizeName(llvm::StringRef name) {
```
Comment (rdzhabarov) [inline lib/Support/Support.cpp]: can you add quick test for this

Comment (beicy) [reply lib/Support/Support.cpp]: I modified the Caffe2ImporterTest.cpp test to verify this case. Do you mean we need to write a separate test for the function only?

Comment (rdzhabarov) [reply lib/Support/Support.cpp]: yup, to cover those cases when it does not start with alpha, when it's empty etc.

**Comment by rdzhabarov** [comment]
to fix `expensive_tests` run you'd need to rebase on latest master.

File: lib/Support/Support.cpp (hunk 3 above)
Comment (beicy) [reply lib/Support/Support.cpp]: Tests added.
