### PR TITLE
[Runtime][OpenCL Device Manager]Added OpenCL Device Manager config object

### LINKED ISSUE #2479: OpenCL device selection broken with new ExecutionEngine/DeviceManager
The new OpenCL deviceManager does not look for command line parameters to select the device. With the executionEngine change to use the deviceManager that means openCL cannot be command line configured.

Going forward we want to extend the DeviceManager interface to accept it's configuration parameters and the ExecutionEngine/HostManager will create these config objects and pass them in when creating the device managers.

### PR DESCRIPTION
**Pull request by gcatron**
*Description*: Added OpenCLDeviceConfig object to OpenCL Device Manager. Also added command line parameter support for OCL device manager when a config object is not provided.
*Testing*: ninja test and resnet-runtime
*Documentation*: NA
Fixes #2479

### CODE REVIEW

File: lib/Backends/OpenCL/OpenCLDeviceManager.h [hunk 1]
```diff
@@ -119,6 +119,15 @@ class OpenCLDeviceManager : public QueueBackedDeviceManager {
   void runFunctionImpl(runtime::RunIdentifierTy id, std::string functionName,
                        std::unique_ptr<Context> ctx, ResultCBTy cb) override;
 };
+
+class OpenCLDeviceConfig : public DeviceConfig {
```
Comment (opti-mix) [inline lib/Backends/OpenCL/OpenCLDeviceManager.h]: Add Doxygen comments.

File: lib/Backends/OpenCL/OpenCLDeviceManager.h [hunk 2]
```diff
@@ -119,6 +119,15 @@ class OpenCLDeviceManager : public QueueBackedDeviceManager {
...
+public:
+  OpenCLDeviceConfig() : DeviceConfig(BackendKind::OpenCL) {}
+  unsigned platformId;
```
Comment (opti-mix) [inline lib/Backends/OpenCL/OpenCLDeviceManager.h]: This class has only public members. Make it a struct or make the data members private (and do not forget the underscores at the end) and provide accessors.

File: lib/Backends/OpenCL/OpenCL.cpp [hunk 3]
```diff
@@ -73,20 +73,20 @@ static const unsigned char kernels_fwd_quantized_conv_cl_src[] = {
...
-               llvm::cl::init(0), llvm::cl::cat(OpenCLBackendCat));
-static llvm::cl::opt<unsigned>
-    deviceId("device", llvm::cl::desc("OpenCL device to be used"),
-             llvm::cl::init(0), llvm::cl::cat(OpenCLBackendCat));
-static llvm::cl::opt<bool> doProfile("opencl-profile",
-                                     llvm::cl::desc("Profile OpenCL kernels"),
-                                     llvm::cl::init(false),
-                                     llvm::cl::cat(OpenCLBackendCat));
-} // namespace
+llvm::cl::opt<unsigned> platformId("platform",
```
Comment (opti-mix) [inline lib/Backends/OpenCL/OpenCL.cpp]: Since this options are global now, may be the names of the variables should be more OpenCL specific? `platformId` and `deviceId` seems too generic for a global variable.

Comment (gcatron) [reply lib/Backends/OpenCL/OpenCL.cpp]: changed to clPlatformId, clDeviceId, and clDoProfile.
