### PR TITLE
 [quantization] fix Tensor zero() and isZero() to respect quantized offset

### LINKED ISSUE #2082: [Quantization/Tensor] 0 should be represented as an offset for quantized numbers
[zero](https://github.com/pytorch/glow/blob/master/include/glow/Base/Tensor.h#L95) and [isZero](https://github.com/pytorch/glow/blob/master/include/glow/Base/Tensor.h#L628) are not properly handled for quantized types.

Taking quantized int8 for example with {Scale, Offset} parameters.
Given that dequantization is calculated as Scale * (x_quantized - Offset), actual zero value should be represented as Offset and not just 0.

### PR DESCRIPTION
**Pull request by nickgg**
*Description*: Per #2082, Tensors zero() to 0 always which is not correct for quantized types which may have a zero offset. This changes zero() to set each item to the offset, and isZero() to check against the offset for quantized types.
*Testing*: All unittests, but especially tensor tests reset and the new test zeroQuantizedTensor.
*Documentation*:
fixes #2082.

### CODE REVIEW

File: include/glow/Base/Tensor.h [hunk 1]
```diff
@@ -93,8 +93,26 @@ class Tensor final {
 
   /// Set the content of the tensor to zero.
   void zero() {
-    std::fill(&getData()[0], &getData()[0] + size() * type_.getElementSize(),
-              0);
+    // quantized tensors should go to their offset
```
Comment (jfix71) [inline include/glow/Base/Tensor.h]: nit: Capitalize sentence and end with period.

File: include/glow/Base/Tensor.h [hunk 2]
```diff
@@ -93,8 +93,26 @@ class Tensor final {
...
+    case ElemKind::Int16QTy: {
+      auto *data = reinterpret_cast<int16_t *>(getData());
+      std::fill(&data[0], &data[0] + size(), (int16_t)type_.getOffset());
+    } break;
+    case ElemKind::Int32QTy: {
+      auto *data = reinterpret_cast<int32_t *>(getData());
+      std::fill(&data[0], &data[0] + size(), (int32_t)type_.getOffset());
+    } break;
+    default:
+      // not quanitized
```
Comment (jfix71) [inline include/glow/Base/Tensor.h]: nit: Capitalize sentence and end with period.

File: tests/unittests/tensorsTest.cpp [hunk 3]
```diff
@@ -652,6 +652,43 @@ TEST(Tensor, insertWithCountAndAxis) {
...
 }
 
+TEST(Tensor, zeroQuanitizedTensor) {
+  Tensor Q8T(ElemKind::Int8QTy, {3, 4, 5, 6}, 127, 0);
+  Tensor Q16T(ElemKind::Int16QTy, {3, 4, 5}, 1234.7, 223);
+  Tensor Q32T(ElemKind::Int32QTy, {3, 4}, 500.4, 53452);
+
+  auto Q8H = Q8T.getHandle<int8_t>();
+  EXPECT_TRUE(Q8H.isZero());
+  for (size_t i = 0; i < 3 * 4 * 5 * 6; i++) {
```
Comment (jfix71) [inline tests/unittests/tensorsTest.cpp]: Here and other loops below:

```suggestion
  for (size_t i = 0, e = Q8H.size(); i < e; i++) {
```

File: tests/unittests/tensorsTest.cpp [hunk 4]
```diff
@@ -652,6 +652,43 @@ TEST(Tensor, insertWithCountAndAxis) {
   }
 }
```
Comment (jfix71) [inline tests/unittests/tensorsTest.cpp]: Can you add a doxygen comment here explaining what the test is doing?

File: tests/unittests/tensorsTest.cpp [hunk 5]
```diff
@@ -652,6 +652,43 @@ TEST(Tensor, insertWithCountAndAxis) {
...
 
+TEST(Tensor, zeroQuanitizedTensor) {
+  Tensor Q8T(ElemKind::Int8QTy, {3, 4, 5, 6}, 127, 0);
+  Tensor Q16T(ElemKind::Int16QTy, {3, 4, 5}, 1234.7, 223);
+  Tensor Q32T(ElemKind::Int32QTy, {3, 4}, 500.4, 53452);
+
+  auto Q8H = Q8T.getHandle<int8_t>();
+  EXPECT_TRUE(Q8H.isZero());
+  for (size_t i = 0; i < 3 * 4 * 5 * 6; i++) {
+    EXPECT_EQ(Q8H.raw(i), 0);
```
Comment (jfix71) [inline tests/unittests/tensorsTest.cpp]: Perhaps you can get the offset from the Tensor's type here and below instead of explicitly writing out the offset? That way it's quite obvious what's going on.

Comment (jfix71) [reply tests/unittests/tensorsTest.cpp]: Huh -- what's the bug? Can you create an issue to track it?

An alternative could be `const int32_t offsetQ8 = 0;` and so on, and then you can use it everywhere (including in initializing each of the tensors).

Comment (nickgg) [reply tests/unittests/tensorsTest.cpp]: No bug currently. I just mean hypothetically if there was a bug in getOffset in the future, since we use it both to write the 'zero' into the buffer and to check that the buffer is 'zero', this test wouldn't give any signal that it was wrong. Using a constant gives us a little more coverage.

I like your alternative though, much clearer.

File: tests/unittests/tensorsTest.cpp [hunk 6]
```diff
@@ -652,6 +652,50 @@ TEST(Tensor, insertWithCountAndAxis) {
   }
 }
 
+/// Verify that tensors that are quantized begin zero'd to their type's offset
+/// and are reset back to that offset.
+TEST(Tensor, zeroQuanitizedTensor) {
```
Comment (rdzhabarov) [inline tests/unittests/tensorsTest.cpp]: typo in `zeroQuanitizedTensor`

Comment (rdzhabarov) [reply tests/unittests/tensorsTest.cpp]: can you also add a test case where you set values to the tensor to be equal to the offset and isZero returns true?
