### PR TITLE
[OnnxModelLoader] Add SAME_UPPER/SAME_LOWER auto_pad modes.

### LINKED ISSUE #2503: [ModelZoo] Support DUC model
Add support for the Dense Upsampling Convolution (DUC) semantic segmentation model in glow (https://github.com/onnx/models/tree/master/models/semantic_segmentation/DUC) and verify via a runnable example we can include in the ModelZoo regression test.

This model requires a different image set than the imagenet images we include with glow (it was trained on the cityscapes dataset), but may be runnable with the ImageClassifier and the right configuration.

This issue blocks #2500.

### PR DESCRIPTION
**Pull request by arunm-git**
*Description*:

Add support for SAME_UPPER and SAME_LOWER auto_pad modes per the spec at
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv

Also applies to AveragePool.

*Testing*:
Added unit tests for VALID/SAME_UPPER/SAME_LOWER.
ninja check

*Issues*:
Related to #2504

### CODE REVIEW

File: lib/Importer/ONNXModelLoader.cpp [hunk 1]
```diff
@@ -208,8 +215,38 @@ llvm::Expected<Pads> getPads(const ArgumentDictionaryTy &dict) {
...
+      // o = floor((i + 2*p - k)/s) + 1
+      // Also, from https://github.com/onnx/onnx/blob/master/docs/Operators.md
+      // output_spatial_shape[i] =
+      //     ceil(input_spatial_shape[i] / strides_spatial_shape[i])
+      // pad_shape[i] =
+      //     (output_spatial_shape[i] - 1) * strides_spatial_shape[i]
+      //         + kernel_spatial_shape[i] - input_spatial_shape[i]
+      // Use the smallest padding possible out of the possible options.
+      std::vector<unsigned_t> pdim(2); // Total Paddding, HW.
+      for (size_t i = 0; i < pdim.size(); i++) {
```
Comment (jackm321) [inline lib/Importer/ONNXModelLoader.cpp]: use something like `(size_t i = 0, size_t e = pdim.size(); i < e;...`

File: lib/Importer/ONNXModelLoader.cpp [hunk 2]
```diff
@@ -208,8 +215,38 @@ llvm::Expected<Pads> getPads(const ArgumentDictionaryTy &dict) {
...
+      // From https://arxiv.org/pdf/1603.07285.pdf 2.4,
+      // o = floor((i + 2*p - k)/s) + 1
+      // Also, from https://github.com/onnx/onnx/blob/master/docs/Operators.md
+      // output_spatial_shape[i] =
+      //     ceil(input_spatial_shape[i] / strides_spatial_shape[i])
+      // pad_shape[i] =
+      //     (output_spatial_shape[i] - 1) * strides_spatial_shape[i]
+      //         + kernel_spatial_shape[i] - input_spatial_shape[i]
+      // Use the smallest padding possible out of the possible options.
+      std::vector<unsigned_t> pdim(2); // Total Paddding, HW.
```
Comment (jackm321) [inline lib/Importer/ONNXModelLoader.cpp]: This probably should be small vector size 2 but the other things (sdim, kdim, etc) aren't either so up to you

File: lib/Importer/ONNXModelLoader.cpp [hunk 3]
```diff
@@ -553,6 +592,14 @@ llvm::Error ONNXModelLoader::loadPool(const ONNX_NAMESPACE::NodeProto &op,
     kernels[1] = Ty->dims()[3];
   }
 
+  // NHWC
+  std::vector<unsigned_t> idim(2);
```
Comment (jackm321) [inline lib/Importer/ONNXModelLoader.cpp]: The `idimHW` name above is move helpful

File: tests/unittests/OnnxImporterTest.cpp [hunk 4]
```diff
@@ -199,16 +199,19 @@ TEST(onnx, importUniBroadcastMultiOutput) {
...
-/// Test loading conv op from a ONNX model.
-/// The input is N*C*H*W (1*1*3*3), the kernels is {2, 2},
-/// strides is {1, 1}, pads is {1, 1, 1, 1}, group is 1.
-TEST(onnx, importConv) {
+/// Helper method to run the Conv operator test cases.
+/// \p filename contains the model .onnxtxt.
+/// \p expectedDims: output Tensor dimensions.
+/// \p expectedValues : output Tensor values expected.
+static void convTestHelper(std::string &filename,
+                           std::vector<size_t> &expectedDims,
```
Comment (jackm321) [inline tests/unittests/OnnxImporterTest.cpp]: llvm::ArrayRefs

File: tests/unittests/OnnxImporterTest.cpp [hunk 5]
```diff
@@ -252,12 +255,53 @@ TEST(onnx, importConv) {
   EE.compile(CompilationMode::Infer, F);
   EE.run(bindings);
   auto result = bindings.get(graphOutputVar)->getHandle();
+  EXPECT_TRUE(result.dims().vec() == expectedDims);
+  for (size_t i = 0; i < expectedDims.size(); i++)
```
Comment (jackm321) [inline tests/unittests/OnnxImporterTest.cpp]: Use braces for for loop
You mean to loop over the expectedValues.size() right?

Comment (jackm321) [reply tests/unittests/OnnxImporterTest.cpp]: Also same thing with `size_t e =  expectedValues.size()`

Comment (arunm-git) [reply tests/unittests/OnnxImporterTest.cpp]: Good catch. Done.

**Comment by arunm-git** [comment]
Added tests for AveragePool. I was mistaken when I mentioned GlobalAveragePool - doesn't apply there (the code invocation is the same and does the right thing, but there's no padding for that operator).
